# =====================================================
# AI Knowledge Assistant - Application Configuration
# =====================================================

application:

  # Generate dataset from configured sources
  dataset_generation:
    enabled: true

  # Delete existing vector database before indexing
  rebuild_vector_db:
    enabled: true

  # Create embeddings and store in vector database  
  vector_indexing:
    enabled: true

  # Query vector database using LLM
  chat:
    enabled: true

chunking:
  chunk_size: 1000
  chunk_overlap: 200

embedding:
  provider: huggingface
  model: sentence-transformers/all-MiniLM-L6-v2
  batch_size: 32

vector_db:
  type: chroma
  path: ./vectorstore/chroma_db
  collection: knowledge_base

retrieval:
  top_k: 3

llm:
  #provider: gemini
  #model: gemini-3.6-flash
  #temperature: 0
  provider: groq
  model: llama-3.3-70b-versatile
  temperature: 0
  

deepeval_judgellm:
  #provider: gemini
  #model: gemini-3.6-flash
  #temperature: 0
  #provider: claude
  #model: claude-sonnet-4-6
  #temperature: 0
  provider: groq
  model: llama-3.1-8b-instant
  temperature: 0
